#pragma once
#include "stm32u0xx_hal.h"
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Describe a pin to keep active while preparing for sleep */
typedef struct { GPIO_TypeDef* port; uint16_t pin; } KeepPin;

/**
 * Provide the whitelist of pins to keep active across GPIO “analogization”.
 * Call once during init (or whenever the list changes).
 */
void GPIO_Sleep_SetKeepPins(const KeepPin* pins, size_t count);

/** Enable all GPIO clocks (handy before analogizing whole ports). */
void GPIO_EnableAllClocks(void);

/** Build a bitmask for the given port from the current KEEP list. */
uint32_t build_keep_mask(GPIO_TypeDef* port);

/** Set every pin of 'port' to ANALOG/NOPULL except the pins set in 'keep_mask'. */
void port_to_analog_except(GPIO_TypeDef* port, uint32_t keep_mask);

/** Put all non-KEEP pins on all ports into ANALOG/Hi-Z (simple low-power prep). */
void GPIO_PrepareForSleep_Simple(void);

/** Restore GPIO configuration after wake (calls your MX_GPIO_Init). */
void GPIO_RestoreAfterWake_Simple(void);

/* MX_GPIO_Init is provided by your project (generated by CubeMX). */
void MX_GPIO_Init(void);

int GPIO_IsKeep(const KeepPin* keep, size_t keep_len, GPIO_TypeDef* port, uint16_t pin);
void MX_GPIO_ReInit_Except(const KeepPin* keep, size_t keep_len);

#ifdef __cplusplus
}
#endif
